### ISSUE TITLE
App Killed or Suspend

### ISSUE THREAD

**Issue by ErickB14** [ZeroJian/ZJLocation#1]
What happend when the app is killed (forced by the user) or suspend . How I can to get the location in this case?

**Comment by ZeroJian** [comment]
maybe the CLLocationManager method -(void)startMonitoringSignificantLocationChange ,can use this case
you can see this: http://mobileoop.com/getting-location-updates-for-ios-7-and-8-when-the-app-is-killedterminatedsuspended

but i'm not sure this method now you can use
